package com.myproject.onlinecounter.model;
// Generated Feb 21, 2016 10:19:27 PM by Hibernate Tools 4.3.1



/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int categoryid;
     private String description;
     private Integer tax;

    public Category() {
    }

	
    public Category(int categoryid) {
        this.categoryid = categoryid;
    }
    public Category(int categoryid, String description, Integer tax) {
       this.categoryid = categoryid;
       this.description = description;
       this.tax = tax;
    }
   
    public int getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(int categoryid) {
        this.categoryid = categoryid;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getTax() {
        return this.tax;
    }
    
    public void setTax(Integer tax) {
        this.tax = tax;
    }




}


