package com.myproject.onlinecounter.model;
// Generated Feb 21, 2016 10:19:27 PM by Hibernate Tools 4.3.1

import java.util.Set;




/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int orderid;
     private int totalwithouttax;
     private int totalsalestax;
     private Set<Orderitem> items;
     
    public Orders() {
    }

    public Orders(int orderid, int totalwithouttax, int totalsalestax) {
       this.orderid = orderid;
       this.totalwithouttax = totalwithouttax;
       this.totalsalestax = totalsalestax;
    }
   
    public int getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(int orderid) {
        this.orderid = orderid;
    }
    public int getTotalwithouttax() {
        return this.totalwithouttax;
    }
    
    public void setTotalwithouttax(int totalwithouttax) {
        this.totalwithouttax = totalwithouttax;
    }
    public int getTotalsalestax() {
        return this.totalsalestax;
    }
    
    public void setTotalsalestax(int totalsalestax) {
        this.totalsalestax = totalsalestax;
    }

    public Set<Orderitem> getItems() {
        return items;
    }

    public void setItems(Set<Orderitem> items) {
        this.items = items;
    }




}


